### ISSUE TITLE
KKTIX event API 非 https，無法使用

### ISSUE THREAD

**Issue by YuerLee** [MOLi-rocks/MOLi-rocks.github.io#10]
因 MOLi.Rocks 已使用 https，造成 KKTIX event API 無法讀取。

**Comment by YuerLee** [comment]
已向 KKTIX  [提出建議](http://support.kktix.com/forums/229961-kktix-general-discussion/suggestions/13174752-組織公開活動列表的-api-是否可以使用-https)

**Comment by YuerLee** [comment]
如果 KKTIX 不改，我們是否只能自己寫個後端來拿資料，自己開 API？

**Comment by zxp86021** [comment]
@passerbyid 可以，但是好像有點瞎(?

**Comment by YuerLee** [comment]
@BlueT 請賜教。

**Comment by bluet** [comment]
衝了呀

**Comment by zxp86021** [comment]
利用 nginx 的 proxy_pass 功能將 `http://moli.kktix.cc/events.json` 改掛到 `https://moli.rocks:8888`
