### ISSUE TITLE
新增子網域

### ISSUE THREAD

**Issue by zxp86021** [MOLi-rocks/MOLi-rocks.github.io#12]
1. 新增 slack.moli.rocks 來放 slack 自動邀請
2. 新增 bot.moli.rocks 來放 MOLi Bot

**Comment by bluet** [comment]
都指到 mola.moli.rocks 這台嗎？

**Comment by zxp86021** [comment]
是的

**Comment by bluet** [comment]
Done.
Using CNAME to point to mola.moli.rocks.
Please check 20mins later.

**Comment by zxp86021** [comment]
已確認，謝謝練老師
