### ISSUE TITLE
開新子網域 api.moli.rocks

### ISSUE THREAD

**Issue by YuerLee** [MOLi-rocks/MOLi-rocks.github.io#14]
為因應 #10 要開 API，請求開新的子網域：`api.moli.rocks`。

**Comment by YuerLee** [comment]
麻煩網管 @BlueT 或 @zxp86021 了。

**Comment by zxp86021** [comment]
@BlueT 才是網管，我什麼都不會QQ

**Comment by bluet** [comment]
好哦，要指到哪個 IP?

**Comment by zxp86021** [comment]
mola

**Comment by bluet** [comment]
抱歉我 miss 掉了這個 issue.
設好了。

api     CNAME   mola.moli.rocks.    5m

**Comment by zxp86021** [comment]
confirmed
