### ISSUE TITLE
moli.rocks 及各子網域新增 ipv6 支援

### ISSUE THREAD

**Issue by zxp86021** [MOLi-rocks/MOLi-rocks.github.io#16]
如題，因為學校網路 ipv4 有時候會雷爆，所以希望可以有 ipv6 (server 已有 ipv6)

**Comment by bluet** [comment]
ok 我今晚處理

**Comment by bluet** [comment]
我之前已經有設定了耶

 bluet@Titania  ~  host mola.moli.rocks     2016年04月30日 (週六) 19時42分28秒
mola.moli.rocks has address 163.22.17.180
mola.moli.rocks has IPv6 address 2001:e10:6840:17::180
