### ISSUE TITLE
新增 blog.moli.rocks 子網域

### ISSUE THREAD

**Issue by zxp86021** [MOLi-rocks/MOLi-rocks.github.io#19]
請增加 blog.moli.rocks 子網域指向 mola 給 @passerbyid 要架的 ghost blog 使用

**Comment by zxp86021** [comment]
Done, THX

$ nslookup blog.moli.rocks
Server:         2001:4860:4860::8888
Address:        2001:4860:4860::8888#53

Non-authoritative answer:
Name:   blog.moli.rocks
Address: 163.22.17.180

**Comment by bluet** [comment]
Welcome
