### ISSUE TITLE
增加 beta.moli.rocks 子網域

### ISSUE THREAD

**Issue by YuerLee** [MOLi-rocks/MOLi-rocks.github.io#21]
請增加 beta.moli.rocks 子網域指向 mola 作為 MOLi 網站測試用途。

**Comment by bluet** [comment]
之前加成 demo 了，難怪開不了...
剛才已經更正，等 DNS propagation 完就能用了

**Comment by bluet** [comment]
可以用這個看 DNS 更新狀況
https://dnschecker.org/#A/beta.moli.rocks

**Comment by BlueT** [comment]
可以用這個看 DNS 更新狀況
https://dnschecker.org/#A/beta.moli.rocks

**Comment by YuerLee** [comment]
OK 了，感謝。
