### ISSUE TITLE
MOLi VM setup

### ISSUE THREAD

**Issue by zxp86021** [MOLi-rocks/MOLi-rocks.github.io#7]
1. 裝 nginx
2. 裝 nodejs
3. 裝 pm2
4. 搬移 moli-IoT Door 服務
5. 搬移 slack 自動邀請 server

**Comment by bluet** [comment]
waiting for NCNU CC approve VM application
@BlueT is waiting the email

**Comment by bluet** [comment]
您好：
    您申請的雲端伺服器已通過審核，詳細資訊如下：
    CPU：2 顆
    記憶體：4 G
    硬碟空間：60 GB
    網路卡數量：1
    作業系統：Ubuntu 14.04.2
    IPv4位址：163.22.17.180
    IPv6位址：2001:e10:6840:17::180

domain name:
mola.moli.rocks
moli.ncnu.edu.tw
兩個都已經啟用

**Comment by bluet** [comment]
目前有幫 @BlueT 和 @zxp86021 開帳號了，需要的人可以講一下

**Comment by passerbyid** [comment]
@BlueT MOLi.rocks 沒有要指嗎

**Comment by bluet** [comment]
http://mola.moli.rocks/
works now

檔案在 /var/www/vhost/moli.rocks/public_html
這目錄就是直接 git clone ...... public_html 出來的
然後 group 是 moli，權限是 group writeable
目前 moli 這個 group 已經把 @zxp86021 和 @BlueT 都加入了

/etc/nginx/sites-available/moli.rocks 和 default 都有設定任何 . 開頭的隱藏檔都 return 404，所以 .git 不會被看到

**Comment by bluet** [comment]
因為是設定 wildcard 所以看何時要轉，我就把 DNS 改一下

**Comment by YuerLee** [comment]
@BlueT  MOLi.rocks 可以轉到 VM 上囉！

**Comment by bluet** [comment]
@passerbyid 帳號已開，加入 moli 群組了。

**Comment by bluet** [comment]
大家在 /var/www/vhost/moli.rocks/public_html 做完事情後，記得下：
  $ chown -R ${USER}:moli ./

別人才能繼續改呀 XD

**Comment by bluet** [comment]
DNS 已設定。
20min~3hrs 後 moli.rocks 就會是新 VM 了。 XD
