### ISSUE TITLE
MOLi Google 地點設定

### ISSUE THREAD

**Issue by focaaby** [MOLi-rocks/MOLi-rocks.github.io#9]
如題，設定 MOLi 的 Google 地點設定

範例： [摩茲工寮](https://www.google.com.tw/maps/place/%E6%91%A9%E8%8C%B2%E5%B7%A5%E5%AF%AE+Mozilla+Community+Space+Taipei/@25.0442266,121.5322393,15z/data=!4m2!3m1!1s0x0:0xfa4585936ffcc86c)

**Comment by YuerLee** [comment]
已申請，等待 Google 的實體驗證明信片中。

**Comment by YuerLee** [comment]
已驗證，已設定。
